apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    #apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: gitops_repository
    value: ssh://git@github.com/nitashav-vmw/ops.git
  - name: gitops_branch
    value: main
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_server_address
    value: ssh://git@github.com
  - name: gitops_repository_owner
    value: nitashav-vmw
  - name: gitops_repository_name
    value: ops
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
